exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = waybar > /dev/null 2>&1
exec-once = awww-daemon && awww img "$HOME/Pictures/wallpapers/walls/default.jpg" --transition-type none && ln -sf "$HOME/Pictures/wallpapers/walls/default.jpg" "$HOME/.config/hypr/current_wallpaper"
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = swaync
exec-once = hypridle
exec-once = swayosd-server
exec-once = nm-applet --indicator
exec-once = ~/.config/hypr/scripts/closed-window-listener.sh &
