exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = sh -c 'waybar &'
exec-once = swww-daemon
exec-once = swww img "$HOME/Pictures/wallpapers/walls/default.jpg" --transition-type none
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
