windowrule {
  name = xwaylandvideobridge-fixes
  match:class = ^(xwaylandvideobridge)$

  opacity = 0.0 override 0.0 override
  no_anim = on
  no_initial_focus = on
  no_blur = on
}

# Desabilitar blur em tudo exceto o Kitty
windowrule {
  name = disable-blur-others
  match:class = ^(?!kitty).*$

  no_blur = on
}

# Preview flutuante do wallpaper picker (swayimg)
windowrule {
  name = swayimg-picker
  match:class = ^(swayimg-picker)$

  float = on
  size = 500 500
  move = 25% 25%
  no_focus = on
  no_blur = on
  no_shadow = on
}
