windowrule {
  name = xwaylandvideobridge-fixes
  match:class = ^(xwaylandvideobridge)$

  opacity = 0.0 override 0.0 override
  no_anim = on
  no_initial_focus = on
  no_blur = on
}

# Desabilitar blur em tudo exceto o Kitty e Zed
windowrule {
  name = disable-blur-others
  match:class = ^(?!kitty|dev\.zed\.Zed|Zed).*$

  no_blur = on
}

# Zed - transparência para habilitar blur do tema Vesper Blur
windowrule {
  name = zed-blur
  match:class = ^(dev\.zed\.Zed|Zed)$

  opacity = 0.85 override 0.80 override
}
